# Generated by Django 4.2.4 on 2023-08-16 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_genre_game_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='desctiption',
            new_name='description',
        ),
        migrations.AddField(
            model_name='game',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='games.studio'),
        ),
    ]
